### ISSUE TITLE
Getting error output

### ISSUE THREAD

**Issue by jonare77** [bluet/docker-jottacloud#11]
Im getting this output in the container, the jotta generated code are correct.

`Personal login token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Logging in. Please wait...ERROR  Could not login: openid.login: token: server did not recognize the provided credentials                                                                    
expect: spawn id exp3 not open
    while executing
"expect eof"
couldn't read file "remote": no such file or directory`

Can you help me in the right direction. Tried with docker compose on synology and ubuntu.

**Comment by bluet** [comment]
@jonare77 last time I see this error log was because jottacloud auth service was having issue.
Would you mind try to regenerate a new token?
If doesn't work still, wait 1 or 2 days and try again with another new token.

Last time I waited for a few days and it worked again (without changing any code in this project).

If you want to speed up the process, can also try to open a ticket in jotta-cli repo.

If the issue persists for a longer than a week, please let me know and I'll test it again. : 😊

**Comment by jonare77** [comment]
Closed
